# Тут указывается используемый в проекте язык программирования, можно указать несколько
language: python

# Далее, укажите версии python для которых нужно производить сборки
python:
  - "3.7"
  - "3.8"
  - "pypy3"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install pytest-cov
  - pip install pytest-subprocess
  - pip install codecov
  - pip install coloredlogs

install:
  - pip install ".[test]" . # install package + test dependencies

script:
  - pytest

after_success:
  - codecov #